-----------------------------
World size: 1
-----------------------------
python3 imagenet_train_eval.py -a resnet18 --epochs 90 --batch-size 64 --multiprocessing-distributed --world-size 1 --rank 0 /scratch/talbn/imagenet
seed fixed!
ngpus_per_node:  3
[W socket.cpp:558] [c10d] The client socket has failed to connect to [::ffff:224.66.41.62]:23456 (errno: 101 - Network is unreachable).
[W socket.cpp:558] [c10d] The client socket has failed to connect to [::ffff:224.66.41.62]:23456 (errno: 101 - Network is unreachable).
[W socket.cpp:558] [c10d] The client socket has failed to connect to [::ffff:224.66.41.62]:23456 (errno: 101 - Network is unreachable).
[W socket.cpp:558] [c10d] The client socket has failed to connect to 224.66.41.62:23456 (errno: 101 - Network is unreachable).
[E socket.cpp:610] [c10d] The client socket has failed to connect to any network address of (224.66.41.62, 23456).
[W socket.cpp:558] [c10d] The client socket has failed to connect to 224.66.41.62:23456 (errno: 101 - Network is unreachable).
[W socket.cpp:558] [c10d] The client socket has failed to connect to 224.66.41.62:23456 (errno: 101 - Network is unreachable).
[E socket.cpp:610] [c10d] The client socket has failed to connect to any network address of (224.66.41.62, 23456).
[E socket.cpp:610] [c10d] The client socket has failed to connect to any network address of (224.66.41.62, 23456).
Main worker!
Use GPU: 0 for training
Main worker!
Use GPU: 1 for training
Main worker!
Use GPU: 2 for training
Traceback (most recent call last):
  File "imagenet_train_eval.py", line 494, in <module>
    main()
  File "imagenet_train_eval.py", line 117, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/users/mhussein/State-of-Quantization-in-DL/env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/users/mhussein/State-of-Quantization-in-DL/env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/users/mhussein/State-of-Quantization-in-DL/env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/users/mhussein/State-of-Quantization-in-DL/env/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/users/mhussein/State-of-Quantization-in-DL/experiments/imageNet/imagenet_train_eval.py", line 136, in main_worker
    dist.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/users/mhussein/State-of-Quantization-in-DL/env/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 595, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/users/mhussein/State-of-Quantization-in-DL/env/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 212, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/users/mhussein/State-of-Quantization-in-DL/env/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 188, in _create_c10d_store
    return TCPStore(
RuntimeError: The client socket has failed to connect to any network address of (224.66.41.62, 23456). The client socket has failed to connect to 224.66.41.62:23456 (errno: 101 - Network is unreachable).

srun: error: ault42: task 0: Exited with exit code 1
